AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pushes logs, metrics and traces from AWS to Datadog.
Parameters:
  DdApiKey:
    Type: String
    NoEcho: true
    Default: ''
    AllowedPattern: ([0-9a-f]{32}|$^)
    ConstraintDescription: DdApiKey needs to be either empty or a hex string of length
      32
    Description: The Datadog API key. NOT recommended. Provide the API key via DdKmsApiKey
      or DdApiKeySecretArn instead. Refer to the README on the left for details.
  DdKmsApiKey:
    Type: String
    NoEcho: true
    Default: ''
    Description: The KMS-encrypted Datadog API key. Use instead of DdApiKey. KMSKeyId
      must be provided if a customer managed CMK is used for encryption.
  DdApiKeySecretArn:
    Type: String
    NoEcho: true
    Default: ''
    Description: The Secret ARN to fetch the Datadog API key from Secrets Manager.
      Use instead of DdApiKey. KMSKeyId must be provided if a customer managed CMK
      is used for encryption. E.g., arn:aws:secretsmanager:us-east-1:111111111111:secret:DDAPIKEY-C3b2A1.
  KMSKeyId:
    Type: String
    NoEcho: true
    Default: ''
    Description: Required only if the Datadog API key is provided via DdKmsApiKey
      or DdApiKeySecretArn, and a customer managed CMK is used for encryption. E.g.,
      1a2b3c4d-aaaa-1111-bbbb-1a2b3c4d5e6f.
  DdSite:
    Type: String
    Default: datadoghq.com
    AllowedValues:
    - datadoghq.com
    - datadoghq.eu
    ConstraintDescription: DdSite must be datadoghq.com or datadoghq.eu
    Description: Set to datadoghq.eu to send data to the Datadog EU site.
  DdTags:
    Type: String
    Default: ''
    Description: Optional. Add custom tags to the forwarded log entries, comma-delimited
      string, no trailing comma, e.g., env:prod,stack:classic
  FunctionName:
    Type: String
    Default: DatadogForwarder
    Description: The Datadog Forwarder Lambda function name. DO NOT change unless
      you need to install multiple forwarders in the same region for advanced use
      cases.
  ReservedConcurrency:
    Type: Number
    Default: 100
    Description: Reserved concurrency for the Datadog Forwarder Lambda function
  LogRetentionInDays:
    Type: Number
    Default: 90
    Description: CloudWatch log retention for logs generated by the Datadog Forwarder
      Lambda function
Conditions:
  SetDdApiKey:
    Fn::Not:
    - Fn::Equals:
      - Ref: DdApiKey
      - ''
  SetDdKmsApiKey:
    Fn::Not:
    - Fn::Equals:
      - Ref: DdKmsApiKey
      - ''
  SetDdApiKeySecretArn:
    Fn::Not:
    - Fn::Equals:
      - Ref: DdApiKeySecretArn
      - ''
  SetDdTags:
    Fn::Not:
    - Fn::Equals:
      - Ref: DdTags
      - ''
  SetKMSKeyId:
    Fn::Not:
    - Fn::Equals:
      - Ref: KMSKeyId
      - ''
Resources:
  DatadogForwarder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Ref: FunctionName
      Description: Pushes logs, metrics and traces from AWS to Datadog.
      Handler: lambda_function.lambda_handler
      MemorySize: 1024
      Runtime: python3.7
      Timeout: 120
      Layers:
      - Fn::Sub: arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Python37:8
      Environment:
        Variables:
          DD_API_KEY:
            Fn::If:
            - SetDdApiKey
            - Ref: DdApiKey
            - Ref: AWS::NoValue
          DD_KMS_API_KEY:
            Fn::If:
            - SetDdKmsApiKey
            - Ref: DdKmsApiKey
            - Ref: AWS::NoValue
          DD_API_KEY_SECRET_ARN:
            Fn::If:
            - SetDdApiKeySecretArn
            - Ref: DdApiKeySecretArn
            - Ref: AWS::NoValue
          DD_TAGS:
            Fn::If:
            - SetDdTags
            - Ref: DdTags
            - Ref: AWS::NoValue
          DD_SITE:
            Ref: DdSite
      ReservedConcurrentExecutions:
        Ref: ReservedConcurrency
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          Resource: arn:aws:s3:::*
      - Fn::If:
        - SetDdApiKeySecretArn
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn:
              Ref: DdApiKeySecretArn
        - Ref: AWS::NoValue
      - Fn::If:
        - SetKMSKeyId
        - KMSDecryptPolicy:
            KeyId:
              Ref: KMSKeyId
        - Ref: AWS::NoValue
      CodeUri: s3://dd-log-sam-test/5554a0b7349ec17c094a18d3a1acaf82
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${DatadogForwarder}
      RetentionInDays:
        Ref: LogRetentionInDays
Outputs:
  DatadogForwarderArn:
    Description: Datadog Forwarder Lambda Function ARN
    Value:
      Fn::GetAtt:
      - DatadogForwarder
      - Arn
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-DatadogForwarderArn
